server:
  port: 8762
  #port: 8765
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

